import { StyleSheet } from "react-native";


export const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: "flex-start",
        alignItems: "center",
        backgroundColor: "#131314",
    },
    main_extrato: {
        width: "95%",
        height: "20%",
        justifyContent: "flex-start",
        alignItems: "center",
        backgroundColor: "#1b1b1b",
        borderRadius: 10,
        padding: 20,
        marginTop: 40,
    },
    title: {
        fontSize: 15,
        fontWeight: 'bold',
        color: '#c4c7c5',
        alignSelf: 'flex-start',
        marginLeft: 10,
        opacity: 0.8,
        marginTop: 20,
    },
    title_balance: {
        fontSize: 50,
        fontWeight: 'bold',
        color: '#c4c7c5',
        alignSelf: 'center',
        marginLeft: 10,
        opacity: 0.8,
        margin: 20,
    },
    drop_list: {
        width: "95%",
        height: "7%",
        justifyContent: "space-around",
        alignItems: "center",
        backgroundColor: "#1b1b1b",
        borderRadius: 10,
        padding: 20,
        marginTop: 20,
        flexDirection: "row",
    },
    imagem: {
        height: 25,
        width: 25,
        alignSelf: 'center',
    },
    container_image: {
        width: "15%",
        height: "20%",
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#9d9d9d",
        borderRadius: 10,
        padding: 20,
    },
    item: {
        width: '95%',
        backgroundColor: '#5d5d5d',
        padding: 10,
        borderRadius: 10,
        marginTop: 10,
        alignSelf: 'center',
        justifyContent: 'space-around',
        flexDirection: 'row',
    },
    container_view: {
        width: "95%",
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#1b1b1b",
        borderRadius: 10,
        padding: 20,
        marginTop: 20,
        gap: 10,
    },
    text_item: {
        fontSize: 15,
        fontWeight: 'bold',
        color: '#F5F5F5',
        alignSelf: 'center',
        marginLeft: 10,
    },
    container_title: {
        width: "90%",
        height: "7%",
        justifyContent: "space-around",
        alignItems: "center",
        backgroundColor: "#c4c7c5",
        borderRadius: 10,
        padding: 20,
        flexDirection: "row",
    }
})